#Makefile to build all programs in all subdirectories
#
#DIRS is a list of all subdirectories containing makefiles
#(The library directory is first so that the library gets built first)
DIRS =lib\
      fileio
